#   General

allow-external-apps = true

volume-keys = volume
disable-terminal-session-change-toast = true
bell-character = ignore

# default-working-directory = /data/data/com.termux/files/home
# hide-soft-keyboard-on-startup = true
# soft-keyboard-toggle-behaviour = enable/disable

# enforce-char-based-input = true
# ctrl-space-workaround = true

### Max 50000. May have negative impact on perf.
# terminal-transcript-rows = 2000
# terminal-transcript-rows = 500
terminal-transcript-rows = 5000

# terminal-margin-horizontal=6 # thyme - bent screen
# terminal-margin-horizontal=20 # Pacman - massively
terminal-margin-horizontal=0

shortcut.create-session=ctrl + 7
shortcut.previous-session=ctrl + 5
shortcut.next-session=ctrl + 6

extra-keys-style = all

#   Extra keys

# extra-keys = [[ \
#   {key: TAB, popup: {macro: "CTRL 5", display: "s prv"}}, \
#   {key: ESC, popup: {macro: "CTRL 6", display: "s nxt"}}, \
#   {key: DEL, popup: {macro: "CTRL 7", display: "s new"}}, \
#   {key: '/', popup: 'BACKSLASH'}, \
#   {key: '-', popup: '_'}, \
#   {key: '=', popup: '`'}, \
#   {key: 'CTRL', popup: 'ALT'}, \
#   {key: 'HOME', popup: 'PGUP'}, \
#   {key: 'END', popup: 'PGDN'}, \
#   {key: ':', popup: '|'} \
# ]]

# extra-keys = [[ \
#   {key: TAB, popup: {macro: "CTRL 7", display: "s+"}}, \
#   {key: ESC, popup: {macro: "CTRL 5", display: "s<"}}, \
#   {key: DEL, popup: {macro: "CTRL 6", display: "s>"}}, \
#   {key: '/', popup: 'BACKSLASH'}, \
#   {macro: "", display: " ", popup: 'KEYBOARD'}, \
#   {macro: "", display: " ", popup: 'DRAWER'}, \
#   {key: 'CTRL', popup: 'ALT'}, \
#   {key: 'HOME', popup: 'PGUP'}, \
#   {key: 'END', popup: 'PGDN'}, \
#   {key: ':', popup: '|'} \
# ]]

extra-keys = [[ \
  {key: TAB, popup: {macro: "CTRL 5", display: "<|"}}, \
  {key: ESC, popup: {macro: "CTRL 6", display: "|>"}}, \
  {key: DEL, popup: {macro: "CTRL 7", display: "|+"}}, \
  {key: '/', popup: 'BACKSLASH'}, \
  {key: '-', popup: '_'}, \
  {key: '=', popup: 'DRAWER'}, \
  {key: 'CTRL', popup: 'ALT'}, \
  {key: 'HOME', popup: 'PGUP'}, \
  {key: 'END', popup: 'PGDN'}, \
  {key: ':', popup: '|'} \
]]
