# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -fno-semantic-interposition -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

MAKEOPTS="-j8 -l9"
EMERGE_DEFAULT_OPTS="--jobs 3"

USE="-X -gtk -gnome -debug -kde zstd"
ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

GENTOO_MIRRORS="https://mirror.meowsmp.net/gentoo/ \
    https://ftp.jaist.ac.jp/pub/Linux/Gentoo/ \
    https://mirrors.tuna.tsinghua.edu.cn/gentoo/"
