inherits = "base16_transparent"

"ui.statusline.normal" = { fg = "white", bg = "gray" }
"ui.statusline.insert" = { fg = "black", bg = "blue" }
"ui.statusline.select" = { fg = "black", bg = "magenta" }
